// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srokpawueetpgclmoehg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyb2twYXd1ZWV0cGdjbG1vZWhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMTE4ODYsImV4cCI6MjA1OTg4Nzg4Nn0.8aJ8dPHat_rs9A1c1gb33dAb9uQblnd0ii29lcVXcns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);